### ISSUE TITLE
Support for android somehow?

### ISSUE THREAD

**Issue by SuperUserockx** [ottomated/CrewLink#108]
it might not be possible to get the same location data from the app's shared memory during the runtime (unless the system was rooted). Nor I think it might be legally possible to edit the original .apk and republish a 3rd party version.

(This is as per my knowledge of android system whish. I am more than happy to be wrong on this.)

**Comment by DispatchCommit** [comment]
This is probably out of scope for this project. It may be possible through the developments done by the NodePolus team since that would allow getting player state directly from a custom server, but since CrewLink reads gamestate directly from memory, it would be extremely difficult to accommodate mobile players.
