### ISSUE TITLE
Version 1.1.4 crashes

### ISSUE THREAD

**Issue by acapple** [ottomated/CrewLink#135]
So yesterday I was playing on crewLink v1.1.2 just fine. Today I go ahead and install crewlink v1.1.4, and run it. the game starts to load just fine, then once it gets to the main menu screen for Among Us. I went ahead and tried to reinstall Among Us, reinstalling crewlink, restarting my computer and no luck. The only hint of an error is a bunch of random characters that show up for a split second. I managed to get a screenshot of the random characters. The screenshot I got is attached. Any ideas for how I should fix it?

![error](https://user-images.githubusercontent.com/53370883/101236483-95736600-369f-11eb-9ebe-2e9985313af8.png)

**Comment by mrhyde1st** [comment]
I think this might tie into the latest version of Among Us.  They have released versions 12.3 and CrewLink is giving me an error it's not compatible with it currently.

**Comment by sjoerd108** [comment]
@acapple I've seen this happen to a friend of mine as well, though I haven't been able to deduce what the problem is. I do know what fixed it. Try the following:

1. Close crewlink
2. Navgigate to your AppData folder (you can do this with **Windows Button + R**, type %AppData% and hit enter)
3. Go into the folder "Roaming"
4. Delete the folder "crewlink"
