### ISSUE TITLE
Among Us Update

### ISSUE THREAD

**Issue by WatermelonFarmz** [ottomated/CrewLink#19]
The mod just doesn’t work anymore following the terms of service thing in the recent among us patch.

**Comment by ryantheleach** [comment]
v2020.11.17s

**Comment by WatermelonFarmz** [comment]
Do you know when this could be fixed? I'm only asking because I've fallen in love with this addition to the game.

**Comment by ryantheleach** [comment]
@WatermelonFarmz have a little patience, the author or someone that knows how to get the offsets first needs to get the new offsets, then update the server repo, deploy it, AS WELL as an alternate method of fetching the offsets from the server, since it appears innersloth are quite happy to push updates without properly updating the game version in values, which means an alternate version checking / identification mechanism for the client needs to be implemented.

**Comment by ryantheleach** [comment]
@ottomated You updated the server component to have updated offsets, but people are going to need an update to crewlink, uninstall crewlink and all cached data, or some other way to clear the cached data.

**Comment by ryantheleach** [comment]
The temporary fix now the offsets are updated is to nuke your C:\Users\xxx\AppData\Roaming\crewlink\ folder, and redo your settings.

**Comment by walter-is-yes** [comment]
> 
> 
> The temporary fix now the offsets are updated is to nuke your C:\Users\xxx\AppData\Roaming\crewlink\ folder, and redo your settings.

how would i go about "nuking it"? do i delete the entire folder?

**Comment by ryantheleach** [comment]
yes

**Comment by Bunga44** [comment]
I don't know why this worked and I had the same issue, but I installed the 1.1.1 version of crewlink and opened it. After I opened among us using crewlink, it updated to the most recent version. So I quit out of the game and quit crewlink then reopened it. It now says 1.1.2. and now it works for me and all my friends. hope this helps.

**Comment by kewin100** [comment]
still doesnt work fo rme

**Comment by ryantheleach** [comment]
You have a different issue then originally described. This issue was *specifically* about the 'secret' update among us pushed that didn't change the version number.

Among us is currently on v2020.12.5s
