### ISSUE TITLE
Android/Emulator Support

### ISSUE THREAD

**Issue by GitPrateek** [ottomated/CrewLink#227]
**Suggestion**: A large number of users use an **emulator** to play Among Us on their PC. An **Android/iOs app** for the same would help a lot of people experience this cool feature as well.

Would love to know what are your plans/thoughts regarding that. @ottomated

**Comment by DorCoMaNdO** [comment]
That is never going to happen, it's been requested a few times now, getting all the required information from an emulator, or a mobile app in general, is a lot more complex, I don't mean to be rude, but I'm sure you could find $5 to buy the game on Steam, it's really inexpensive.

**Comment by BenCat07** [comment]
I can imagine you'd need root access for that, and it just sounds like it's not worth it. Still sad that my friend - who does not own a pc - won't be able to use this, means my friend group will not be able to use it

**Comment by DorCoMaNdO** [comment]
You would need root, and the structure of a mobile OS, even a Linux based one, is going to be trickier to work with, the most viable solution for the current implementation of CrewLink would be an Xposed module because you could potentially directly patch the game, but it would likely still take a lot of maintenance. The best alternative would be a custom server for among us, but CrewLink operates without doing so, but in the future there could be an easier and more reliable adaptation that it could perhaps be an option.
