### ISSUE TITLE
Display all player information

### ISSUE THREAD

**Issue by neil-lobo** [ottomated/CrewLink#27]
Lobby data is given to the client (which was probably used for debugging purposes) which you can derive player locations, isImpostor field, etc. I won't put the method to get this information in this issue since it takes 2 seconds to perform, so message me on discord techno#0970

**Comment by ryantheleach** [comment]
It's my bet that you are talking about using electrons in built debugging capability to pull data out of CrewLink?

The Crewlink client requires the information in order to correctly track the game state, as well as future features like 'haunting', else give this responsibility to the CrewLink relay server, which is only really designed for minimum data transfer needed to connect the various clients together (it's literally 89 lines of code https://github.com/ottomated/CrewLink-server/blob/master/src/index.ts) .

It's possible that Among Us may remove the information from the game clients at some point in the future, in which case CrewLink is going to have to come up with alternate solutions.

In my view, there's very little difference in using this method then cheating yourself with your own hack/mod.
So the blame is entirely on the user that is cheating / the Among Us developers to not include the information in the game client.

**Comment by neil-lobo** [comment]
What I was leaning towards was that crewlink outputs this data in the console so it's accessible to anyone. I assume it's just one console.log line that was not removed by mistake or something.

**Comment by ryantheleach** [comment]
I can't reproduce the error, using the release build of Crewlink.

![image](https://user-images.githubusercontent.com/141554/100451156-d6e79c80-3106-11eb-967a-2957e30e2770.png)

**Comment by ryantheleach** [comment]
I played around with it some more, and it does indeed look like some (public) debugging functionality has been left in.

![image](https://user-images.githubusercontent.com/141554/100451601-9d636100-3107-11eb-916d-d9aac60d08be.png)

However, I was only able to get it to trigger on Connect MENU (5)

If it only ever triggers on menu it's pretty harmless as it's outdated gamestate info, but I can't 100% confirm that it does.

**Comment by ryantheleach** [comment]
https://github.com/ottomated/CrewLink/blob/8272732c932f5f4fc8e7848981617a1b096687d5/src/renderer/Voice.tsx#L150

**Comment by neil-lobo** [comment]
When you refresh the electron view with ctrl+r it logs the current game state in the console. At first, I thought it wasn't a good idea for me to say how to view the information but I then realized that the chances of someone looking in the issues tab and using it are slim to none. I would have tried to make a pull request myself but I couldn't get a build of the application due to some installation issues that I didn't really want to deal with and I didn't want to merge a new change before I could compile the application for myself
