### ISSUE TITLE
add a match making servese for the server and clients of the app

### ISSUE THREAD

**Issue by Littlemac123** [ottomated/CrewLink#33]
It would be nice so its easier to find other people using the mod as well

**Comment by neil-lobo** [comment]
At the moment, there is no central server that all clients connect to. Currently, the repo author is hosting a public relay server (which is the default server in the client) that can handle up to 100 players before it crashes, which is why there is also a repo to set up [your own relay server](https://github.com/ottomated/CrewLink-server). A completely new server would have to be created for this.

**Comment by ottomated** [comment]
Out of scope
