### ISSUE TITLE
Trouble Accessing Crewlink voice channels with certain ISPs

### ISSUE THREAD

**Issue by TheChick** [ottomated/CrewLink#450]
Hello! My friends and I tried using Crewlink, in a group of 6, 4 of them could connect with little issue, two of us were able to connect to the voice channel (no red rings around our character portrain in Crewlink) but could not hear anyone else (Crewlink was able to detect our voices because we could see the green circle around us).

After testing out changing microphones and speaker settings, my friend tried switching internet connection to another ISP since she had two, and it suddenly started working for her. 

I am not sure if this is a problem solvable on your end, but help on resolving this would be appreciated. It seems some ISPs cannot connect to the voice channel properly.

**Comment by CStafford-14** [comment]
I think I'm having the same issue... (I'm using the Linux fork, but I think the nature of the issue is what's more important)

I tried CrewLink with 2 other people, persons A and B. Person A and I could hear each other, A and B could hear each other, but B and I couldn't hear each other. I think this is an ISP issue because I have had issues in the past when connecting to a server on B's network (Minecraft) from my home, but no issue elsewhere. When I get the chance, I'll test CrewLink on another network.

Also, I'll test this with a 4th person who I know we can access each other's networks (again, Minecraft.)
