### ISSUE TITLE
[BUG REPORT] Ghosts can talk with the still living/some players can be heard over the whole map

### ISSUE THREAD

**Issue by Play-Tiger** [ottomated/CrewLink#478]
In almost every round the ghosts can talk to the still surviving, only very occasionally it does not work.
A few players can be heard over the whole map, but this happened only rarely and usually CTRL+R fixes the problem again.
It happens almost every round that you can't hear people, so quite often you have to press CTRL+R, but this person who pressed CTRL+R then always hears only one particular person. Only when everyone in the round presses CTRL+R can they all hear each other again.
You can see almost all bugs in the stream here, but it is in German. [https://www.twitch.tv/videos/854076719]
Only the bug that everyone has to press CTRL+R does not appear in the stream. We only noticed it later in the evening.
We all used Windows 10 when we used Crewlink and we all used the latest version 1.2.0.. We also tested different servers, namely the standard server crew.link and s1 and s2. But that did not fix any of the problems.
I don't know exactly how to reproduce this, since it just happens.

**Comment by ottomated** [comment]
Needs reproduction instructions

**Comment by Play-Tiger** [comment]
All the problems mentioned just happen when playing and cannot be reproduced or triggered in any other way. That is why I have not added any instructions.

**Comment by pilot51** [comment]
This has been happening regularly and randomly with my group of 5-8 every few rounds. We've been using a v1.2.1 server I set up on a headless Debian 8 box. I'm using the [Linux client from zbanks](https://github.com/zbanks/CrewLink/releases/tag/v1.2.1) on Mint 20 and I believe everyone else uses Windows 10. So far I see no indication that it depends on the OS, though I haven't yet been the one that was heard everywhere.

Tonight was the second time we used CrewLink (and it's great!). Out of roughly 15 rounds, I recall 2 rounds on Polus where I could hear one person throughout the map, a different person for each. Apparently everyone heard the same person for the first occurrence and only I heard the second one. It returns to normal after the round ends and we return to the lobby. Some of the others experienced it on other rounds. It happened to the game host on another round (I forget the map) and they tried restarting CrewLink to fix it during the round, but that appeared to cause some people to have connection issues in the client and everyone went back to Discord for emergency discussions for the rest of the round.

I don't know any steps to reproduce, but it seems to start early in the round if not from the very start. My first suspicion was maybe a lost packet for positional data breaking things, since sometimes internet isn't very stable at my place or where my server is, but I don't have any real evidence to support that theory.

I understand the frustration of not having a clue how to reproduce a bug. Even as a solo developer where I typically have to write and maintain all the issues that other people run into at work, I personally leave such issues open for visibility until either a fix is found or the last report was so long ago that it's safe to assume it resolved itself. Just because it can't be reproduced doesn't mean it's not a problem, and leaving the issue open would help others find it who may have more useful information if not actually know how to reproduce.
