### ISSUE TITLE
Allow host to control overlay

### ISSUE THREAD

**Issue by nathanee** [ottomated/CrewLink#547]
Please allow the host to determine whether an overlay of who is speaking is displayed outside of meetings.

**Is your feature request related to a problem? Please describe.**

I have found that the overlay removes much of the ability and fun of trying to be sneaky or playful. It also gives advantage to crew upon seeing that an imposter may be breathing nearby. Having crew see exactly who is speaking to whom even at the furthest reaches of their sound radius is not fair for imposters.

**Describe the solution you'd like**

Have the host override the overlay status as an option, eg host sets overlay as off. Like the other host only options.

**Describe alternatives you've considered**

Have far away players show up on overlay as ??? with unknown colour.

**Additional context**

**Comment by beautivile** [comment]
Can't they just cheat by having their crewlink open and watch that too?  Seems like if people don't want to be heard they need to use the mute button

**Comment by nathanee** [comment]
Yes they could, but it is not overlayed on your screen. Also most people will be playing the game in full screen on one monitor so it isn't much of an issue.

**Comment by billyjbryant** [comment]
I tend to agree here, I think it would be preferred, IMO for the overlay to only show up during meetings or at least be controllable in some way. If you can see whomever is in your radius because their microphone picked up a sound, it makes you privy to information you would not have already had using the in-game mechanics. Another solution might be to disable the overlay during events like lights-out, coms sabotage and to dynamically change the overlay draw distance based on the player's visibility. IE, if the player wouldn't be able see the person on screen, they shouldn't be able to see that it is that person talking.

**Comment by ottomated** [comment]
I won't be implementing this because it doesn't make sense for the host to be able to change other people's interfaces. There are genuine reasons for wanting to display the overlay and having the host override that is bad UX. If you're having this problem you can use a different microphone, enable PTT, ask your friends to disable the overlay, etc.

**Comment by nathanee** [comment]
I understand that there are genuine reasons to have the overlay be present and controllable by players but it also provides information that they should not necessarily have. Without visual confirmation of who they are speaking to.
The request is not for host to control the interface, just for the host to be able to disable the information gained from seeing the popup telling players who is talking through the walls.
Your meeting overlay-highlight is brilliant though btw. It is super helpful and shouldn't be adjustable by host.

**Comment by nathanee** [comment]
Or if a player cannot see who is talking. They shouldn't get an overlay saying who is talking, they should need to get closer. As billy said above.
Like maybe what you are hearing is from the edge of your hearing radius it displays a question mark for who is talking.
