### ISSUE TITLE
Audio panning not working

### ISSUE THREAD

**Issue by kyleawayan** [ottomated/CrewLink#55]
I've taken a look at your [`calculateVoiceAudio` function in `Voice.tsx`](https://github.com/ottomated/CrewLink/blob/8cec56e3988a47fa006d9b98b6c5066bf81518bc/src/renderer/Voice.tsx#L60), and it looks like it's working. I'm able to console log `panPos`, and it's updating when I'm moving around.

So I think the issue here has something to do with the actual panning modification to the audio. I'm on Windows 10 Pro 19041.630 and everyone I hear is in mono.

**Comment by ottomated** [comment]
Can other people reproduce this?

**Comment by Gabe-H** [comment]
Yes, I also can on the latest windows 10 home edition (not at computer at the moment)

**Comment by kyleawayan** [comment]
All the people that I was playing with said that they couldn't hear panning audio either

**Comment by pau101** [comment]
@ottomated The output is mono because because the panner node is connected to a single channel script node. This line should specify 2 and 2 for in/out channels, or the audio graph could be restructured: https://github.com/ottomated/CrewLink/blob/357b8f8a2eaee7116653042538e0303ba2dbd977/src/renderer/vad.ts#L60

**Comment by kyleawayan** [comment]
@pau101 Your fixed worked! Tested it out with @Gabe-H and it works.

I have made a [pull request](https://github.com/ottomated/CrewLink/pull/64) for this.
