### ISSUE TITLE
Playing Among Us on Epic Games

### ISSUE THREAD

**Issue by PhastTraveler** [ottomated/CrewLink#637]
I only have Among Us in Epic Games and I can't use the crewlink because of that.

**Comment by NotLinkedes** [comment]
the game code and the green circle with the among us character wont show up after buying on epic games for free

**Comment by MatadorProBr** [comment]
Do not create another issue as already have 11 issues on the same subject, this is caused because of the new update of Among Us that ended up breaking the CrewLink and have to wait for Ottomated to solve this problem but have a solution for this, look the issue in [#623](https://github.com/ottomated/CrewLink/issues/623#issuecomment-793888862) that solves this problem.
